src/Entity/SnoUser.php
<?php

namespace App\Entity;

use App\Repository\SnoUserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: SnoUserRepository::class)]
class SnoUser implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $username;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private string $email;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/FigureController.php
<?php

namespace App\Controller;

use App\Entity\SnowComment;
use App\Entity\SnowFigure;
use App\Form\CommentFormType;
use App\Form\FigureFormType;
use App\Manager\FigureManagerInterface;
use App\Repository\SnowCommentRepository;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class FigureController extends AbstractController
{
    #[Route('/figures/list', name: 'figures_list')]
    public function figuresList(FigureManagerInterface $figureManager): Response
    {
        $figureList = $figureManager->getFiguresList();

        return $this->render('figure/listFigures.html.twig', [
            'controller_name' => 'FigureController',
            'figures' => $figureList,
        ]);
    }

    #[Route('/figure/{slug}', name: 'figure_show')]
    public function index(Request $request, FigureManagerInterface $figureManager, SnowFigure $figure, TranslatorInterface $translator): Response
    {
        // Back to home page if the requested figure is not published
        if (!$figure->getPublish()) {
            $message = $translator->trans('This figure is not published!');
            $this->addFlash('danger', $message);

            return $this->redirectToRoute('home');
        }

        $user = $this->getUser();
        $comment = new SnowComment();
        $form = $this->createForm(CommentFormType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid() && $user) {
            try {
                $figureManager->newComment($comment, $figure, $user);
            } catch (Exception) {
                $message = $translator->trans('System error: please try again');
                $this->addFlash('danger', $message);

                return $this->redirectToRoute('figure_show', [
                    'slug' => $figure->getSlug(),
                ]);
            }
            $message = $translator->trans('your comment has been added');
            $this->addFlash('success', $message);

            return $this->redirectToRoute('figure_show', [
                'slug' => $figure->getSlug(),
            ]);
        }

        $offset = max(0, $request->query->getInt('offset', 0));
        $paginator = $figureManager->getComment($figure, $offset);

        return $this->render('figure/index.html.twig', [
            'controller_name' => 'FigureController',
            'figure' => $figure,
            'commentForm' => $form->createView(),
            'comments' => $paginator,
            'previous' => $offset - SnowCommentRepository::PAGINATOR_PER_PAGE,
            'next' => min(count($paginator), $offset + SnowCommentRepository::PAGINATOR_PER_PAGE),
        ]);
    }

    #[Route('/new', name: 'figure_new')]
    #[Route('/figure/edit/{slug}', name: 'figure_edit')]
    public function new(SnowFigure $figure = null, Request $request, FigureManagerInterface $figureManager, TranslatorInterface $translator): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        if (!$figure) {
            $figure = new SnowFigure();
        }

        $user = $this->getUser();
        $form = $this->createForm(FigureFormType::class, $figure);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $isCreated = $figureManager->handleFigure($figure, $user);
                if ($isCreated) {
                    $message = $translator->trans('The figure has been created successfully');
                    $this->addFlash('success', $message);
                } else {
                    $message = $translator->trans('The figure has been modified');
                    $this->addFlash('success', $message);
                }
            } catch (Exception) {
                $message = $translator->trans('System error: please try again');
                $this->addFlash('danger', $message);

                return $this->redirectToRoute('figure_edit');
            }

            return $this->redirectToRoute('figures_list', [
                'slug' => $figure->getSlug(),
            ]);
        }

        return $this->render('figure/managedFigure.html.twig', [
            'figureForm' => $form->createView(),
            'figure' => $figure,
            'editMode' => null !== $figure->getId(),
        ]);
    }

    #[Route('/figure/delete/{slug}', name: 'figure_delete')]
     public function deleteFigure(SnowFigure $figure, FigureManagerInterface $figureManager, TranslatorInterface $translator): Response
     {
         $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

         $hasBeenRemoved = $figureManager->removeFigure($figure);

         if ($hasBeenRemoved) {
             $message = $translator->trans('Figure could not be deleted');
             $this->addFlash('danger', $message);
         } else {
             $message = $translator->trans('Figure has been deleted');
             $this->addFlash('success', $message);
         }

         return $this->redirectToRoute('figures_list');
     }
}

templates/figure/_delete_form.html.twig
<!-- Modal -->
<div class="modal fade" id="staticBackdrop{{figure.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="staticBackdropLabel">{% trans %}Deletion of{% endtrans %} {{ figure.name}}</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body mx-auto">
				<p>{% trans %}Are you sure you want to delete this figure?{% endtrans %}</p>
				<p></p>
				<p>
					<i>{% trans %}(It is possible to unpublish it only){% endtrans %}</i>
				</p>
				<p></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" data-bs-dismiss="modal">{% trans %}Cancel{% endtrans %}</button>
				<form method="post" action="{{ path('figure_delete', {'slug': figure.slug}) }}">
					<input type="hidden" name="_method" value="DELETE">
					<button class="btn btn-danger btn buttonCard">{% trans %}Confirm{% endtrans %}</button>
				</form>
			</div>
		</div>
	</div>
</div>

templates/figure/_form.html.twig
{{ form_start(figureForm) }}

{{ form_widget(figureForm._token) }}

{{ form_row(figureForm.name, { label: 'Title'|trans }) }}

{{ form_row(figureForm.description, { label: 'Description'|trans }) }}

{{ form_row(figureForm.snowCategory, { label: 'Category'|trans }) }}

{{ form_row(figureForm.publish, { label: 'Publish'|trans }) }}

<hr>
{# PHOTOS  #}
<div class="d-flex justify-content-start mb-1">
    <div class="mr-2">
        {{ form_label(figureForm.images, 'Pictures'|trans) }}
    </div>
    <button type="button"
        class="add-another-collection-widget btn-sm btn-primary mr-2"
        data-list-selector="#image-list"><i class="fas fa-plus"></i></button>
    </button>
    <button class="btn-sm btn-primary text-center d-lg-none" type="button" data-toggle="collapse" data-target="#collapseImage" aria-expanded="false">
        {% trans %}Show list{% endtrans %}
    </button> 
</div>
         
<ul class="list-inline" id="image-list"
    data-prototype="{{ form_widget(figureForm.images.vars.prototype)|e }}"
    data-widget-tags="{{ '<li class="list-group-item"></li>'|e }}"
    data-widget-counter="{{ figureForm.images|length }}">
    <div class="collapse dont-collapse-sm  text-center" id="collapseImage">
    {% for image in figureForm.images %}    
        {{ form_errors(image) }}
        <li class="list-inline-item image-list-miniature">
            {% if image.vars.data is not null and image.vars.data.src is not null %}
            <img src="{{ asset(image.vars.data.src) }}" alt="" width="250" height="150">
            {% endif %}
            {{ form_widget(image) }}
            <button type="button" class="collection-item-delete"><i class="iconify" data-icon="bx:bx-trash" style="color: red;" data-width="25"></i></button>
        </li>
    {% endfor %}
    </div>    
</ul>
{# PHOTOS  #}


<hr>
{# VIDEOS #}
<div class="d-flex justify-content-start mb-1">
    <div class="mr-2">
        {{ form_label(figureForm.videos, 'Videos'|trans) }}
    </div>       
    <button type="button"
        class="add-another-collection-widget btn-sm btn-primary mr-2"
        data-list-selector="#video-list"><i class="fas fa-plus"></i></button>
    </button>
    <button class="btn-sm btn-primary text-center d-lg-none" type="button" data-toggle="collapse" data-target="#collapseVideo" aria-expanded="false">
        {% trans %}Show list{% endtrans %}
    </button>  
</div>
    
<ul class="list-group px-1" id="video-list"
    data-prototype="{{ form_widget(figureForm.videos.vars.prototype)|e }}"
    data-widget-tags="{{ '<li class="list-group-item"></li>'|e }}"
    data-widget-counter="{{ figureForm.videos|length }}">
    <div class="collapse dont-collapse-sm" id="collapseVideo">
    {% for video in figureForm.videos %}
        {{ form_errors(video) }}
        <li class="list-group-item">
            {{ form_widget(video) }}
            <button type="button" class="collection-item-delete"><i class="iconify" data-icon="bx:bx-trash" style="color: red;" data-width="25"></i></button>
        </li>
    {% endfor %}
    </div>
</ul>
{# VIDEOS #}    

<hr>
{# BOUTON SAVE #}  
<div class="blockcenter">
    <button class="btn btn-primary">{{ button_label|default('Save'|trans) }}</button>
</div>
{# BOUTON SAVE #}

{{ form_end(figureForm, { "render_rest": false }) }}


{% block textJS %}
{# https://symfony.com/doc/current/reference/forms/types/collection.html #}
<script>
$(document).ready(function () {
    $('.add-another-collection-widget').click(function (e) {
        var list = $($(this).attr('data-list-selector'));
        // Try to find the counter of the list or use the length of the list
        var counter = list.data('widget-counter') || list.children().length;

        // grab the prototype template
        var newWidget = list.attr('data-prototype');
        // replace the "__name__" used in the id and name of the prototype
        // with a number that's unique to your url
        // end name attribute looks like name="figure[videos][2]"
        newWidget = newWidget.replace(/__name__/g, counter);
        // Increase the counter
        counter++;
        // And store it, the length cannot be used if deleting widgets is allowed
        list.data('widget-counter', counter);

        // create a new list element and add it to the list
        var newElem = $(list.attr('data-widget-tags')).html(newWidget);
        newElem.appendTo(list);

        // also add a remove button
        newElem.append('<button type="button" class="collection-item-delete"><i class="iconify" data-icon="bx:bx-trash" style="color: red;" data-width="25"></i></button>');
        newElem.find('.collection-item-delete').click(function(e) {
            e.preventDefault();          
            $(this).parent().remove();
            return false;
        });
        bsCustomFileInput.init();
    });    

    //remove item button
    $('.collection-item-delete').click(function(e) {
        e.preventDefault();          
        $(this).parent().remove();
        return false;
    });

});    
</script>
{% endblock %}

templates/figure/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Figure{% endtrans %} / {{ figure.name }}
{% endblock %}

{% block body %}
	{% if figure.images is empty %}
		<section id="heronoimage">
			<div class="heronoimage-container" data-aos="fade-up">
				<h1>{{ figure.name }}</h1>
				<a href="#description" class="btn-get-started scrollto">
					<i class="bx bx-chevrons-down"></i>
				</a>
			</div>
		</section>
	{% else %}
		<!-- ======= Hero Section ======= -->
		{% for image in figure.images %}
			{% if loop.first %}
				<section id="herofigure" style="background: linear-gradient(rgba(55, 142, 181, 0.5), rgba(55, 142, 181, 0.2)),
					url('{{ image.src }}') top center;background-size: cover;position: relative;background-attachment: fixed;">
				{% endif %}
			{% endfor %}
			<div class="herofigure-container" data-aos="fade-up">
				<h1>{{ figure.name }}
				</h1>
				<a href="#description" class="btn-get-started scrollto">
					<i class="bx bx-chevrons-down"></i>
				</a>
			</div>
		{% endif %}
	</section>
	<!-- End Hero -->

	<main
		id="main">
		<!-- ======= Breadcrumbs Section ======= -->
		<section id="description" class="breadcrumbs">
			<div class="container">
				<div class="d-flex justify-content-between align-items-center">
					<h2>{{ figure.name }}</h2>
					{% if is_granted('ROLE_USER') %}
						<div>
							<a href="{{ path('figure_edit', {'slug': figure.slug}) }}" title="Editer">
								<i class="iconify" data-icon="bx:bx-edit" style="color: green;" data-width="25"></i>
							</a>
							<a data-bs-toggle="modal" data-bs-target="#staticBackdrop{{figure.id}}" title="Supprimer">
								<i class="iconify" data-icon="bx:bx-trash" style="color: red;" data-width="25"></i>
							</a>
						</div>
					{% endif %}
					<ol>
						<li>
							<a href="{{ path('home') }}">{% trans %}Home{% endtrans %}</a>
						</li>
						<li>
							<a href="{{ path('figures_list')}} ">{% trans %}Figures{% endtrans %}</a>
						</li>
						<li>{% trans %}Figure details:{% endtrans %}
							{{ figure.name }}</li>
					</ol>
				</div>
			</div>
		</section>
		<!-- Breadcrumbs Section -->

		<!-- Modal -->
		{% include ('figure/_delete_form.html.twig') %}

		<!-- ======= Figure Details Section ======= -->
		<section id="portfolio-details" class="portfolio-details">
			<div class="container">
				<div class="row gy-4">
					<div class="text-center my-1">
						<button class="btn btn-primary text-center d-lg-none" type="button" data-toggle="collapse" data-target="#collapseIndicators" aria-expanded="false">
							{% trans %}See pictures{% endtrans %}
						</button>
					</div>
					<div class="col-lg-8 collapse dont-collapse-sm" id="collapseIndicators">
						{% if figure.images is empty and figure.videos is empty %}
							<img
							class="d-block mx-auto img-responsive" src="\img\pas-d-image-disponible.jpg" alt="">
							{# <img src="\img\pas-d-image-disponible.jpg" class="img-fluid" alt="image par défaut"> #}
						{% else %}
							<div id="carouselTrick" class="carousel" data-ride="carousel">
								<div class="carousel-inner d-flex align-items-center">
									{% for image in figure.images %}
										<div class="carousel-item{% if loop.first %} active {% endif %}">
											<img class="d-block mx-auto img-responsive" src="{{ image.src }}" alt="">
										</div>
									{% endfor %}
									{% for video in figure.videos %}
										<div class="carousel-item{% if figure.images is empty and loop.first %} active {% endif %}">
											<div class="embed-responsive embed-responsive-16by9">
												<iframe class="embed-responsive-item" src="{{ video.url }}" allowfullscreen></iframe>
											</div>
										</div>
									{% endfor %}
								</div>

								<div class="carousel-indicators d-block mx-auto">
									<div class="collapse dont-collapse-sm" id="collapseIndicators">
										<div id="carouselIndicators" class="carousel slide" data-ride="carousel">
											{% set i = 0 %}
											<div class="scrolling-wrapper row flex-row flex-nowrap mt-2 pb-2">
												{% for image in figure.images %}
													<div class="col-2" data-target="#carouselTrick" data-slide-to="{{ i }}">
														<img src="{{ image.src }}" class="img-fluid" alt="">
													</div>
													{% set i = i + 1 %}
												{% endfor %}
												{% set v = i %}
												{% for video in figure.videos %}
													{% set urlParts = ( video.url |split('embed/',2)) %}
													{% set urlId = urlParts[1] %}
													<div class="col-2" data-target="#carouselTrick" data-slide-to="{{ v }}">
														<img
														src="http://i3.ytimg.com/vi/{{ urlId }}/hqdefault.jpg" class="img-fluid" alt="">
													{#  afficher une miniature pour chaque vidéo #}
													</div>
													{% set v = v + 1 %}
												{% endfor %}
											</div>
										</div>
									</div>
								</div>
							</div>
						{% endif %}
					</div>

					<div class="col-lg-4">
						<div class="portfolio-info">
							<h3>{% trans %}Figure Information{% endtrans %}</h3>
							<ul>
								<li>
									<strong>{% trans %}Category{% endtrans %}
									</strong>:
									{{ figure.snowcategory.name }}</li>
								<li>
									<strong>{% trans %}Written by{% endtrans %}
									</strong>:
									{{ figure.snowuser.username }}</li>
								<li>
									<strong>{% trans %}Created on{% endtrans %}
									</strong>:
									{{ figure.createdAt|date('Y/m/d'|trans) }}</li>
								{% if figure.editedAt %}
									<li>
										<strong>{% trans %}Modified on{% endtrans %}
										</strong>
										:
										{{ figure.editedAt ? figure.editedAt|date('Y/m/d'|trans) : '' }}</li>
								{% endif %}
							</ul>
						</div>
					</div>

					<div class="col-lg-12">
						<div class="portfolio-description">
							<h2>{% trans %}Description{% endtrans %}</h2>
							<p>{{ figure.description }}
							</p>
						</div>
					</div>

					<div class="pt-5">
						{% if comments|length > 0 %}
							<h3 class="mb-5">{% trans %}Comment(s){% endtrans %}</h3>
							<ul class="comment-list">
								{% for comment in comments %}
									<li class="comment">
										<div class="vcard bio">
											{% if comment.snowuser.avatar is not null %}
												<img src="{{ comment.snowuser.avatar }}" alt="Free Website Template by Free-Template.co">
											{% else %}
												<img src="/img/avatardefaut.jpg" alt="image par defaut">
											{% endif %}
										</div>

										<div class="comment-body">
											<h3>{{ comment.snowuser.username }}
											</h3>
											<div class="meta">{% trans %}Posted the{% endtrans %}
												{{ comment.createdAt ? comment.createdAt|date('Y/m/d h:i a'|trans) : '' }}</div>
											<p>{{ comment.content }}
											</p>
										</div>
									</li>
								{% endfor %}

								{# Pagination comments #}
								<hr my-1>
								{% if previous >= 0 %}
									<a href="{{ path('figure_show', {'slug': figure.slug, offset: previous}) }}">
										<i class="fas fa-backward shadow-sm p-3 mb-5 bg-white rounded"></i>
									</a>
								{% endif %}
								{% if next < comments|length %}
									<a href="{{ path('figure_show', {'slug': figure.slug, offset: next }) }}">
										<i class="fas fa-forward shadow-sm p-3 mb-5 bg-white rounded">
											{% trans %}See more comm....{% endtrans %}</i>
									</a>
								{% endif %}
							{% else %}
								<div class="text-center text-primary">
									<h4>{% trans %}No comments have been posted for this figure!{% endtrans %}
										<i class="bi bi-emoji-frown"></i>
									</h4>
								</div>
								<div class="text-center text-primary">
									<h4>{% trans %}Be the first !!!{% endtrans %}
										<i class="bi bi-emoji-smile"></i>
									</h4>
								</div><br>
							{% endif %}
						</ul>
						<!-- END comment-list -->

						<!-- formulaire d'ajout commentaire -->
						{% if is_granted('ROLE_USER') %}

							<div class="comment-form-wrap pt-5">
								<h3 class="mb-5">{% trans %}Leave a comment :{% endtrans %}</h3>
								{{ form_start(commentForm) }}
								{{ form_row(commentForm.content) }}
								<button type="submit" class="btn-primary">{% trans %}Send{% endtrans %}</button>
								{{ form_end(commentForm) }}
							</div>
						{% else %}
							<div class="text-center">
								<a href="{{ path('app_login') }}">
									<button class="btn-primary">{% trans %}Leave a comment ? Log in!{% endtrans %}</button>
								</a>
							</div>
						{% endif %}
						<br><br>
					</div>
				</div>
			</div>
		</section>
		<!-- End Figure Details Section -->
	</main>
	<!-- End #main -->
{% endblock %}

{% block textJS %}
	<script>
		$('.carousel').carousel({interval: 240000})
	</script>
{% endblock %}

templates/figure/listFigures.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{% trans %}Figures: List{% endtrans %}
{% endblock %}

{% block body %}

	<!-- ======= Hero Section form ======= -->
	<section id="herofigurelist">
		<div id="portfolio" class="herofigurelist-container" data-aos="fade-up">

			<div class="section-title">
				<h1>{% trans %}List of Figures{% endtrans %}</h1>
			</div>

			<div class="col-lg-10 text-white text-left opacity-75">
				<div class="table-responsive">
					<table class="table table-info table-striped">
						<thead>
							<tr>
								{% if is_granted('ROLE_USER') %}
									<th>{% trans %}Figure name{% endtrans %}</th>
									<th class="d-none d-lg-table-cell">{% trans %}Excerpt Description{% endtrans %}</th>
									<th class="d-none d-lg-table-cell">{% trans %}Created on{% endtrans %}</th>
									<th>{% trans %}Published{% endtrans %}</th>
									<th>{% trans %}Management{% endtrans %}</th>
								{% else %}
									<th>{% trans %}Figure name{% endtrans %}</th>
									<th class="d-none d-lg-table-cell">{% trans %}Excerpt Description{% endtrans %}</th>
									<th>{% trans %}Created on{% endtrans %}</th>
								{% endif %}
							</tr>
						</thead>
						<tbody>
							{% for figure in figures %}
								<tr>
									{% if is_granted('ROLE_USER') %}
										<td>
											<a href="{{ path('figure_show', {'slug': figure.slug}) }}">
												<h7 class="card-title">{{ figure.name }}
												</h7>
											</a>
										</td>
										<td class="d-none d-lg-table-cell">{{ figure.description|striptags|slice(0, 130)|raw }}...</td>
										<td class="d-none d-lg-table-cell">{{ figure.createdAt ? figure.createdAt|date('Y/m/d'|trans) : '' }}</td>
										<td>{{ figure.publish ? 'Yes'|trans : 'No'|trans }}
										</td>
										<td>{{ include('figure/_delete_form.html.twig') }}
											<a href="{{ path('figure_edit', {'slug': figure.slug}) }}" title="{% trans %}Edit{% endtrans %}">
												<i class="iconify" data-icon="bx:bx-edit" style="color: green;" data-width="25"></i>
											</a>
											<a data-bs-toggle="modal" data-bs-target="#staticBackdrop{{figure.id}}" title="{% trans %}Remove{% endtrans %}">
												<i class="iconify" data-icon="bx:bx-trash" style="color: red;" data-width="25"></i>
											</a>
										</td>
									{% else %}
										{% if figure.publish %}
											<td>
												<a href="{{ path('figure_show', {'slug': figure.slug}) }}">
													<h7 class="card-title">{{ figure.name }}
													</h7>
												</a>
											</td>
											<td class="d-none d-lg-table-cell">{{ figure.description|striptags|slice(0, 155)|raw }}...</td>
											<td>{{ figure.createdAt ? figure.createdAt|date('d/m/Y') : '' }}</td>
										{% endif %}
									{% endif %}
								</tr>
							{% else %}
								<tr>
									<td colspan="7">{% trans %}There are no figures{% endtrans %}</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</section>
	<!-- End Hero -->
	<main id="main"></main>
{% endblock %}

templates/figure/managedFigure.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{% if editMode %}
		{% trans %}Editing a Figure{% endtrans %}
	{% else %}
		{% trans %}Creating a Figure{% endtrans %}
	{% endif %}
{% endblock %}

{% block body %}
	<!-- ======= Hero Section form ======= -->
	<section id="heronewfigure">
		<div id="portfolio" class="hero-container" data-aos="fade-up">

			<div class="section-title">
				{% if editMode %}
					<h1>{% trans %}Editing a Figure{% endtrans %}</h1>
				{% else %}
					<h1>{% trans %}Creating a Figure{% endtrans %}</h1>
				{% endif %}
			</div>

			<div class="col-lg-5 text-white text-left font-weight-bold">

				{% if editMode %}
					{{ include('figure/_form.html.twig', {'button_label': 'Validate the modification'|trans}) }}
				{% else %}
					{{ include('figure/_form.html.twig', {'button_label': 'Validate the creation'|trans}) }}
				{% endif %}


			</div>
		</div>
	</section>
	<!-- End Hero -->
	<main id="main"></main>
{% endblock %}